version: 2.1

orbs:
  example: decoch/hello@dev:first
  line: decoch/line@dev:4

jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - run: "echo 'testing building...'"
    - example/hello:
        username: "decoch"
    - line/notify:
        message: "hello from orb"
        mentions: "柴田 直人,冨永 晃史"

workflows:
   main:
     jobs:
     - build
