version: 2.1

orbs:
  line: decoch/line@dev:11

jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - line/notify:
        message: "notification test for the Line orb"
        sticker-package-id: 1
        sticker-id: 1

workflows:
   main:
     jobs:
     - build
