version: 2.1

orbs:
  line: decoch/line@0.0.3

jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - line/notify:
        message: "Notification test for the Line orb"
        sticker-package-id: '1'
        sticker-id: '1'

workflows:
   main:
     jobs:
     - build
