version: 2.1

orbs:
  line: decoch/line@dev:10

jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - run: "echo 'testing building...'"
    - line/notify:
        message: "hello from orb"
        sticker-package-id: "1"
        sticker-id: "1"

workflows:
   main:
     jobs:
     - build
