version: 2.1

orbs:
  example: decoch/hello@dev:first

jobs:
  build:
    docker:
    - image: bash
    steps:
    - run: "echo 'testing building...'"
    - example/hello:
        username: "deccoch"

workflows:
   main:
     jobs:
     - build
